version: "3.4"
services:
  postgres-backend:
    image: "postgres:alpine"
    volumes:
      - ./data/postgres-backend:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db3mw"
    ports:
      - "5432:5432"

  backend:
    build:
      context: "./3mw-backend-service/"
      dockerfile: docker/development.Dockerfile
    ports:
      - 8000:8080
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/db3mw"
      POSTGRES_DB: "db3mw"
      POSTGRES_HOST: "postgres-backend"
      POSTGRES_USER: "postgres"
    volumes:
      - ./3mw-backend-service:/app
    restart: always
    depends_on:
      - postgres-backend

  frontend:
    build:
      context: "./3mw-frontend-service/"
      dockerfile: docker/Dockerfile
    volumes:
      - ./3mw-frontend-service:/app
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./3mw-frontend-service/src/3mw_frontend_service/build:/var/www/frontend
    depends_on:
      - backend